channels:
- conda-forge
dependencies:
- python=3.10.16
- pip<=24.3.1
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==2.2.0
  - packaging==24.2
  - pandas==2.2.3
  - psutil==6.1.1
  - pyyaml==6.0.2
  - scikit-learn==1.6.0
  - scipy==1.14.1
name: mlflow-env
